local_config = {
    "argv": ["--local"],
    "data_dir": "/mnt/expansion/Datasets/",
    "rir_root": "/mnt/d/VUT/Deepfakes/Datasets/rirs_noises/",
    "mlaad": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_sample.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
    },
    "mlaad_single": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/train.csv",
        "dev_protocol": "mlaad4sourcetracing/dev.csv",
        "eval_protocol": "mlaad4sourcetracing/eval.csv",
    },
    "mlaad_minimal": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_minimal.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
    },
    "mlaad_intermediate": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
    },
    "mlaad_curated": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_curated.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_complete_FFCosine.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s123_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s123_FFCosine.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s222_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s222_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s123_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s123_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s222_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s222_FFCosine.csv",
    },
    "mlaad_curriculum_rival_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_speaker_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_speaker_complete_FFCosine.csv",
    },
    "mlaad_curriculum_rival_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s123.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s123.csv",
    },
    "mlaad_curriculum_rival_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s222.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s222.csv",
    },
    "stopa": {
        "train_subdir": "STOPA",
        "dev_subdir": "STOPA",
        "eval_subdir": "STOPA",
        "train_protocol": "Trials/protocols",
        "dev_protocol": "Trials/protocols",
        "eval_protocol": "Trials/protocols",
    },
    "batch_size": 6,
    "lstm_batch_size": 4,
    "num_epochs": 5,
    "eval_batch_size_multiplier": 2,
    "train_num_workers": 4,
    "dev_num_workers": 4,
    "train_prefetch_factor": 2,
    "dev_prefetch_factor": 4,
    "pin_memory": True,
    "persistent_workers": True,
}

metacentrum_config = dict(local_config)
metacentrum_config["argv"] = ["--metacentrum"]

sge_config = {
    "argv": ["--sge"],
    "data_dir": "/mnt/strade/ifirc/Datasets/",
    "rir_root": "/mnt/strade/istanek/datasets/",
    "mlaad": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_05pct.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
    },
    "mlaad_single": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/train.csv",
        "dev_protocol": "mlaad4sourcetracing/dev.csv",
        "eval_protocol": "mlaad4sourcetracing/eval.csv",
    },
    "mlaad_intermediate": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
    },
    "mlaad_curated": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_curated.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
    },
    "mlaad_hardmined_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
    },
    "mlaad_directional_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_complete_FFCosine.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s123_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s123_FFCosine.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s222_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s222_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s123_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s123_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s222_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s222_FFCosine.csv",
    },
    "mlaad_curriculum_rival_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_speaker_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_speaker_complete_FFCosine.csv",
    },
    "mlaad_curriculum_rival_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s123.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s123.csv",
    },
    "mlaad_curriculum_rival_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s222.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s222.csv",
    },
    "mlaad_directional_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
    },
    "stopa": {
        "train_subdir": "STOPA",
        "dev_subdir": "STOPA",
        "eval_subdir": "STOPA",
        "train_protocol": "Trials/protocols",
        "dev_protocol": "Trials/protocols",
        "eval_protocol": "Trials/protocols",
    },
    "batch_size": 24,
    "lstm_batch_size": 4,
    "num_epochs": 10,
    "eval_batch_size_multiplier": 2,
    "train_num_workers": 12,
    "dev_num_workers": 16,
    "train_prefetch_factor": 4,
    "dev_prefetch_factor": 6,
    "pin_memory": True,
    "persistent_workers": True,
}

karolina_config = {
    "argv": ["--karolina"],
    "data_dir": "/scratch/project/dd-25-3/Datasets/",
    "rir_root": "/scratch/project/dd-25-3/Datasets/",
    "mlaad": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_05pct.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
    },
    "mlaad_single": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/train.csv",
        "dev_protocol": "mlaad4sourcetracing/dev.csv",
        "eval_protocol": "mlaad4sourcetracing/eval.csv",
    },
    "mlaad_intermediate": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
    },
    "mlaad_curated": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_curated.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified_seed42.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified_seed42.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_complete_FFCosine.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s123_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s123_FFCosine.csv",
    },
    "mlaad_curriculum_hardmined_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s222_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_hardmined_s222_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_complete_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s123_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s123_FFCosine.csv",
    },
    "mlaad_curriculum_directional_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s222_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_directional_s222_FFCosine.csv",
    },
    "mlaad_curriculum_rival_ffcosine": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_speaker_complete_FFCosine.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_speaker_complete_FFCosine.csv",
    },
    "mlaad_curriculum_rival_ffcosine_s123": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s123.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s123.csv",
    },
    "mlaad_curriculum_rival_ffcosine_s222": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s222.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCosine_s222.csv",
    },
    "mlaad_curriculum_rival_ffmulticlass": {
        "train_subdir": "MLAAD",
        "dev_subdir": "MLAAD",
        "eval_subdir": "MLAAD",
        "train_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCMulticlass.csv",
        "dev_protocol": "mlaad4sourcetracing/pair-protocols-stage1/dev_pairs_stratified.csv",
        "eval_protocol": "mlaad4sourcetracing/pair-protocols-stage1/eval_pairs_stratified.csv",
        "curriculum_easy_protocol": "mlaad4sourcetracing/pair-protocols-stage1/train_pairs_stage1_intermediate.csv",
        "curriculum_hard_protocol": "mlaad4sourcetracing/pair-protocols-stage3/train_pairs_stage3_rival_complete_FFCMulticlass.csv",
        "curriculum_hard_neg_ratio": 0.5,
    },
    "stopa": {
        "train_subdir": "STOPA",
        "dev_subdir": "STOPA",
        "eval_subdir": "STOPA",
        "train_protocol": "Trials/Trials_protocols",
        "dev_protocol": "Trials/Trials_protocols",
        "eval_protocol": "Trials/Trials_protocols",
    },
    "batch_size": 20,
    "lstm_batch_size": 4,
    "num_epochs": 50,
    "eval_batch_size_multiplier": 2,
    "train_num_workers": 12,
    "dev_num_workers": 16,
    "train_prefetch_factor": 4,
    "dev_prefetch_factor": 6,
    "pin_memory": True,
    "persistent_workers": True,
}
